### ISSUE TITLE
States (eg "nsw", "queensland") don't seem to work in region selector

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/magda-metadata#12]
I expect these will be common spatial filters on searches (esp for state govts) so it would be good to support searching on them.

**Comment by bsimyo** [comment]
it seems that states are now listed but relevant area isn't highlighted on the map - eg search "queensland" or "new south wales" in entry box above map on left

**Comment by AlexGilleran** [comment]
Fixed
