### ISSUE TITLE
inaccurate hitcount

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda-metadata#13]
so if i search http://terria.io/magda-web/build/?q=advisers+by+Australian+securities, it shows for Commonwealth of Australia (Geoscience Australia) there is one result, but as soon as it select that facet, the hitcount for that facet becomes 8125, and the result is `match-part`, it is confusing because it told me there was one result (see screenshot).
<img width="844" alt="screen shot 2016-12-08 at 12 35 31 pm" src="https://cloud.githubusercontent.com/assets/7508939/20994154/dda66204-bd42-11e6-8245-a2a6c0d06d51.png">
<img width="833" alt="screen shot 2016-12-08 at 12 35 39 pm" src="https://cloud.githubusercontent.com/assets/7508939/20994153/dda42944-bd42-11e6-8b4d-1bebf0ed8dfe.png">

**Comment by AlexGilleran** [comment]
Same root cause as https://github.com/TerriaJS/magda-metadata/issues/14, fixed.
