### ISSUE TITLE
facet not adding up

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda-metadata#14]
in first search, on selecting a publisher i got 3 results
<img width="1029" alt="screen shot 2016-12-08 at 11 17 43 pm" src="https://cloud.githubusercontent.com/assets/7508939/21009774/9b18560e-bd9c-11e6-81d3-2f13734b0a63.png">
When i select the second publisher, there should be 3+ 31 = 34 results, but it tells me it has no matching result, and facet hitcount has changed:
<img width="1003" alt="screen shot 2016-12-08 at 11 17 53 pm" src="https://cloud.githubusercontent.com/assets/7508939/21009776/9b45b6b2-bd9c-11e6-93e0-70da50803f29.png">

Is it because the publisher facet is using `and` logic? if we are using and, then why don't we just force user to be able to only select one option at any given time?

**Comment by AlexGilleran** [comment]
> Is it because the publisher facet is using and logic

Yep! Oops.

Fixed now :)
